-- Generated by Calibrate's agent (agent/core.py) from the prompt:
--   "generate a dbt model for monthly revenue by region"
-- Grounded against the real schema returned by get_schema('orders'),
-- get_schema('customer'), get_schema('nation'), get_schema('region').
-- Validated: VERIFIED - see data/calibrate_state.db validation_runs, or
-- run `python -m cli.demo validate examples/monthly_revenue_by_region.sql`.
{{ config(materialized='view') }}

select
    r.r_name as region,
    date_trunc('month', o.o_orderdate) as order_month,
    sum(o.o_totalprice) as total_revenue,
    count(distinct o.o_orderkey) as order_count
from {{ source('tpch', 'orders') }} o
join {{ source('tpch', 'customer') }} c on o.o_custkey = c.c_custkey
join {{ source('tpch', 'nation') }} n on c.c_nationkey = n.n_nationkey
join {{ source('tpch', 'region') }} r on n.n_regionkey = r.r_regionkey
group by 1, 2
order by 1, 2
